---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-verde
description: an atomic system with the mate desktop

# Start with the universal blue minimal base
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - type: dnf
    install:
      packages:
        - podman
        - distrobox
        # Core MATE Desktop packages
        - mate-panel
        - mate-session-manager
        - mate-settings-daemon
        - mate-control-center
        - mate-terminal
        - mate-menu
        - caja
        - mate-desktop
        - mate-backgrounds
        - mate-applets
        - mate-system-monitor
        - mate-notification-daemon
        - mate-power-manager
        - mate-media
        - mate-screensaver
        - mate-sensors-applet
        - marco

        # MATE Applications (basic set)
        - atril
        - engrampa
        - eom
        - pluma
        - mate-calc

        # some basic gnome apps needed for some functionality
        - gnome-software

        # Display manager
        - lightdm
        - lightdm-gtk-greeter
        
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.gitlab.librewolf-community
          - org.onlyoffice.desktopeditors
          - com.github.marhkb.Pods
          - org.gnome.Loupe
          - com.vscodium.codium
        remove:
          - org.mozilla.firefox
      - scope: user
  - type: signing # signs the image
