---
name: fedora-verde
description: an atomic system with the mate desktop

# Start with the universal blue minimal base
base-image: ghcr.io/ublue-os/base-main
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  
  - type: dnf
    install:
      packages:
        - @mate-desktop
        - lightdm
        - lightdm-gtk-greeter
        
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - io.gitlab.librewolf-community
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages
      - type: script
    scripts:
      - |
        #!/bin/bash
        set -ouex pipefail

        # Configure LightDM
        mkdir -p /etc/lightdm/lightdm.conf.d
        cat > /etc/lightdm/lightdm.conf.d/50-mate.conf <<EOF
        [Seat:*]
        user-session=mate
        EOF

        # Enable the LightDM service
        systemctl enable lightdm.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
